name: CI Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Solution
      run: dotnet build
    - name: Run Unit Tests
      run: dotnet test
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        file: ./test/TestResults/TLC.Taxi.Data.Test.lcov.info
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests